# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-node-app
  template:
    metadata:
      labels:
        app: docker-node-app
    spec:
      containers:
      - name: docker-node-app
        image: pranaypranay/docker-node-app:latest
        ports:
        - containerPort: 3000
