name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Set up Docker Hub credentials
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/docker-node-app:latest

      # Run tests (optional)
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest

    needs: build  # Only run deploy job after the build job is successful

    steps:
      # Checkout code (again, in case it's needed in the deploy step)
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SERVER_KEY }}

      # SSH into the server, start Minikube, and deploy the app
      - name: Deploy to Remote Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          if ! minikube status | grep -q "Running"; then
            minikube start --driver=docker || (minikube delete && minikube start --driver=docker)
          fi

            # Set up kubectl (if not already set)
            export KUBEVERSION=$(kubectl version --client -o json | jq -r '.clientVersion.gitVersion')
            if [[ -z "$KUBEVERSION" ]]; then
              curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl"
              chmod +x kubectl
              sudo mv kubectl /usr/local/bin/
            fi

            # Configure kubectl to use Minikube
            kubectl config use-context minikube || kubectl config use-context $(kubectl config current-context)

            # Pull the Docker image from Docker Hub
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/docker-node-app

            # Deploy the app using kubectl (ensure your deployment.yaml is already on the server or part of the repo)
            kubectl apply -f deployment.yaml
            kubectl apply -f service.yaml

            # Expose the service (optional, if needed)
            kubectl expose deployment docker-node-app --type=NodePort --port=3000

            # Get the Minikube service URL (optional, to confirm deployment)
            minikube service docker-node-app --url
          EOF
